FROM golang:alpine as email_service
WORKDIR /usr/src/app
# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
WORKDIR /usr/src/app/cmd/email_server
RUN go build -v -o email_service 
CMD [ "./email_service" ]