version: "3.9" # optional since v1.27.0
services:
  restapi:
    container_name: restapibus
    #image: maulidito/restapibus:v1.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
  mysql:
    container_name: db_mysql_bus
    #image: maulidito/db_mysql_restapibus:v1.3
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_bus
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
#   rabbitmq:
#     container_name: rabbitmq_service
#     image: rabbitmq:3-management
#     restart: always
#     environment:
#       RABBITMQ_DEFAULT_USER: admin
#       RABBITMQ_DEFAULT_PASS: admin
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq
#     networks:
#       - example_net
#     ports:
#       - 5672:5672
#       - 15672:15672
# volumes:
#   rabbitmq_data:
#     external: true
# networks:
#   example_net:
#     external: true
#     driver: bridge
