version: "3.9"  # optional since v1.27.0
services:
  restapi:
    container_name: restapibus
    image: maulidito/restapibus:v1.3
    ports:
      - 8080:8080
    environment:
      - HOST_DB=mysql
    env_file:
      - .env
  mysql:
    container_name: db_mysql_bus
    image: maulidito/db_mysql_restapibus:v1.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_bus
    restart: always

  
