version: "3.9" # optional since v1.27.0
services:
  restapi:
    container_name: restapibus
    image: maulidito/restapibus:v1.5
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - mq_network
      - mysql_network
      - redis_network
    env_file:
      - .env
    restart: on-failure
  email_service:
    container_name: email_service_restapibus
    image: maulidito/email_service:v1.0.1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mq_network
    env_file:
      - .env
    restart: on-failure
  mysql:
    container_name: db_mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_bus
    networks:
      - mysql_network
    restart: on-failure
    # ports:
    #   - 3307:3306
    volumes:
      - restapi_data:/var/lib/mysql
      - ./dump_db/:/docker-entrypoint-initdb.d
  redis:
    container_name: db_redis
    image: redis:alpine
    networks:
      - redis_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping  | grep PONG ||  exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  rabbitmq:
    container_name: mq_rabbit
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mq_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    # ports:
    #   - 5672:5672
    #   - 15672:15672
volumes:
  rabbitmq_data:
    external: false
  restapi_data:
    external: false

networks:
  mysql_network:
    external: false
    driver: bridge
    name: mysql_network
  mq_network:
    external: false
    driver: bridge
    name: mq_network
  redis_network:
    external: false
    driver: bridge
    name: redis_network
