package constant

const CONSUMER_NAME_TICKET = "EMAIL_SERVICE_TICKET"
const CONSUMER_NAME_PAYMENT = "EMAIL_SERVICE_PAYMENT"
const CONSUMER_PAYMENT_WEBHOOK = "CONSUMER_PAYMENT_WEBHOOK"

const QUEUE_TICKET = "QUEUE_NAME_TICKET"
const QUEUE_PAYMENT = "QUEUE_NAME_PAYMENT"
const QUEUE_PAYMENT_WEBHOOK = "CONSUMER_PAYMENT_WEBHOOK"

const TOPIC_TICKET_EMAIL = "TOPIC_TICKET_EMAIL"
const TOPIC_PAYMENT_EMAIL = "TOPIC_PAYMENT_EMAIL"
const TOPIC_PAYMENT_WEBHOOK = "TOPIC_PAYMENT_WEBHOOK"
